Cknieling/serlio release 2.0
Esri/cityengine pull request #15
Opened 2022-06-21 09:32 UTC by chr11115

- Update Serlio examples and teaser image for serlio 2.0 release

2022-06-21 10:29 UTC, mistafunk requested changes

2022-06-21 10:29 UTC, mistafunk commented on _plugins/serlio.md
> +      link: ./assets/files/serlio_street_segment_instructions.txt
* we should insert a first instruction step to explain how/where to unzip the files
* also, if the instructions are not too long, it would be nice to have them directly in the text above and avoid separate txt file

2022-06-21 10:29 UTC, mistafunk commented on _plugins/serlio.md
> +    text: The Favela example demonstrates how a complex CityEngine Rule Package (RPK) is applied on one or more polygons. The provided Maya project includes an Alembic file with shapes from CityEngin
favela v2 -> v3

2022-06-21 11:45 UTC, chr11115 commented on _plugins/serlio.md
> +    text: The Street Segment example demonstrates the main features of Serlio in a compact scene. Starting from various input shapes (street shapes and building/floor footprints), multiple different
fixed

2022-06-21 11:45 UTC, chr11115 commented on _plugins/serlio.md
> +      link: https://github.com/Esri/serlio/releases/download/v2.0.0/street_segment_part1_maya_project_files.zip
added v1

2022-06-21 11:45 UTC, chr11115 commented on _plugins/serlio.md
> +    text: The Favela example demonstrates how a complex CityEngine Rule Package (RPK) is applied on one or more polygons. The provided Maya project includes an Alembic file with shapes from CityEngin
fixed

2022-06-21 15:44 UTC, mistafunk requested changes
Just some small layout tweaks

2022-06-21 15:44 UTC, mistafunk commented on _plugins/serlio.md
> +    text: The Street Segment example demonstrates the main features of Serlio in a compact scene. Starting from various input shapes (street shapes and building/floor footprints), multiple different
Please list the steps with html < ol > tag

2022-06-21 15:44 UTC, mistafunk commented on _plugins/serlio.md
> +    text: The Favela example demonstrates how a complex CityEngine Rule Package (RPK) is applied on one or more polygons. The provided Maya project includes an Alembic file with shapes from CityEngin
same as above

2022-06-21 16:14 UTC, chr11115 commented on _plugins/serlio.md
> +    text: The Street Segment example demonstrates the main features of Serlio in a compact scene. Starting from various input shapes (street shapes and building/floor footprints), multiple different
Now listing the steps with <ol>

2022-06-21 16:15 UTC, chr11115 commented on _plugins/serlio.md
> +    text: The Favela example demonstrates how a complex CityEngine Rule Package (RPK) is applied on one or more polygons. The provided Maya project includes an Alembic file with shapes from CityEngin
see above

2022-06-22 07:37 UTC, mistafunk approved these changes
Let's go.

2022-06-22 09:00 UTC, merged